"""empty message

Revision ID: 308b9faa7083
Revises: b8e1388db076
Create Date: 2017-12-03 02:43:50.738151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308b9faa7083'
down_revision = 'b8e1388db076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
